version: '3.7'
services:
  ipfs:
    image: ctheory/alpine-ipfs:v0.4.18
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 512M
  cidhookd:
    image: jchancehud/cidhookd:latest
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
  nginx:
    image: jchancehud/alpine-nginx:latest
    depends_on:
      - ipfs
      - cidhookd
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    secrets:
      - writewei_cert.pem
      - writewei_privkey.pem
      - writewei_fullchain.pem
    environment:
      - CONFIG_URL=https://raw.githubusercontent.com/writewei/blueprint/master/nginx.conf
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress

secrets:
  writewei_cert.pem:
    external: true
  writewei_privkey.pem:
    external: true
  writewei_fullchain.pem:
    external: true
